### ISSUE TITLE
Use Helm on Kubernetes => failling to pull Image

### ISSUE THREAD

**Issue by cloebig** [Sentinel-One/helm-charts#117]
Hello,

we start try using sentinelone on Kubernetes. The Chart is installed and the Ressources are deployed but run in a Error.

Failed to load logs: container "agent" in pod "sentinelone-agent-2g4cz" is waiting to start: trying and failing to pull image
Reason: BadRequest (400)

we use Terraform to deploy

```
resource "helm_release" "sentinelone" {
  name              = "sentinelone"
  repository       = "https://sentinel-one.github.io/helm-charts"
  chart               = "s1-agent"
  namespace     = kubernetes_namespace.sentinelone.metadata.0.name
  version            = "23.2.1"
  create_namespace = true

  values = [yamlencode({
    configuration = {
      cluster = {
        name = "<clustername>"
      }
    }
    secrets = {
      # imagePullSecret = "s1-secret" # not used
      site_key = {
        value = "<secret>"
      }
    }
    nodeSelector ={
      "key" = "systemservices"
    }
  })]
}
```

Please can you help to solve?

BR

**Comment by danisevas** [comment]
@cloebig 
My hanch tells me you haven't provided the correct image location (or repository and tag).
For more help, please reach out to support via the proper channels.

**Comment by cloebig** [comment]
Hello @danisevas 

many thanks for the fast reply. 

Okay, please tell us what are correct Image Location and tag? Or what are right proper Channels?
The Provided Examples here, than are incorrect?

BR
