### ISSUE TITLE
Agent logging at `debug` (not `info`) by default

### ISSUE THREAD

**Issue by MPV** [Sentinel-One/helm-charts#166]
It seems the agents (but not the helper) logs at `debug` level by default (and not `info` as it says it should default to):

- https://github.com/Sentinel-One/helm-charts/blob/393d67400be08bf66c73a3b15d20e91a753bdd84/charts/s1-agent/values.yaml#L25
- https://github.com/Sentinel-One/helm-charts/blob/393d67400be08bf66c73a3b15d20e91a753bdd84/charts/s1-agent/templates/NOTES.txt#L4-L9

Since we were seeing `[debug]` logs (and millions of lines per agent per hour), until we explicitly set `configuration.env.agent.log_level` to `info`.

**Comment by oded-s1** [comment]
The default log level is info.
