### ISSUE TITLE
Helm lint failing

### ISSUE THREAD

**Issue by sarath2210** [Sentinel-One/helm-charts#30]
I am trying to perform helm lint but getting the below error.
==> Linting charts/sentinelone
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: s1-agent/templates/common/secrets.yaml:12:3: executing "s1-agent/templates/common/secrets.yaml" at <fail "The site_key.value does not look like a valid site/group token. You must use a site token/group token exported from your console (under the desired site/group scope => Site Info/Group Info. Make sure to copy the full string and not omit any trailing '=' characters.">: error calling fail: The site_key.value does not look like a valid site/group token. You must use a site token/group token exported from your console (under the desired site/group scope => Site Info/Group Info. Make sure to copy the full string and not omit any trailing '=' characters.

**Comment by danisevas** [comment]
@sarath2210  fixed and merged to master.
Will be available from the next release (22.3 ea2)
