### ISSUE TITLE
Docker Images for 21.10.3 are missing

### ISSUE THREAD

**Issue by felixcontant** [Sentinel-One/helm-charts#38]
The newly updated chart `v21.10.3` uses images `ga-21.10.3`, but they are not available.

Steps to reproduce:
```
$ docker pull docker.pkg.github.com/s1-agents/cwpp_agent/s1agent:ga-21.10.3
Error response from daemon: manifest unknown
```

**Comment by nelashvili** [comment]
@felixcontant, they are in your console and you need to download the tar, load it and upload it to your own private repo as documented in the installation guide.
