### ISSUE TITLE
Helm chart should allow setting PriorityClass

### ISSUE THREAD

**Issue by timspeetjens** [Sentinel-One/helm-charts#42]
When a Kubernetes cluster does not have sufficient resources, the s1agent DaemonSet and Helper may not run, because they
run with default priority 0.

To ensure correct operation, the helm chart should allow setting a PriorityClass, for both Agent and Helper, so an admin can choose to run these with system/cluster critical priority.

**Comment by danisevas** [comment]
@timspeetjens THis feature is merged to the master branch and will be available in the next release (22.3.2)
