### ISSUE TITLE
K8S Security Configuration Issues

### ISSUE THREAD

**Issue by brendan-s1** [Sentinel-One/helm-charts#5]
InfoSec scanned the helm charts associated with this project and determined that there are several security findings, some urgent, some less so.

Please see the attached.

**Comment by Jiafi** [comment]
Also getting this issue.

**Comment by Jiafi** [comment]
https://github.com/Sentinel-One/helm-charts/blob/master/charts/s1-agent/templates/agent/daemonset.yaml#L25 Also getting a security finding here.  Would like to be able to specify this.
