### ISSUE TITLE
Typo in the S1_HEAP_TRIMMING_INTERVAL environment variable

### ISSUE THREAD

**Issue by fcontant-stingray** [Sentinel-One/helm-charts#81]
The chart defines a `S1_HEAP_TRIMMING_INTERVAL` env variable, but the `/opt/deployment.sh` script in the `cwpp_agent/s1agent` image consume `S1_HEAP_TRIMMIG_INTERVAL` (Notice the missing 'N').

/opt/deployment.sh
```
if [[ "${S1_HEAP_TRIMMING_ENABLE}" == "true" ]]; then
    sudo /opt/sentinelone/bin/sentinelctl heap_trimming state set on
    sudo /opt/sentinelone/bin/sentinelctl heap_trimming interval set "${S1_HEAP_TRIMMIG_INTERVAL}"
fi
```

Resulting in this error at startup when setting `S1_HEAP_TRIMMING_ENABLE` to true:

```
/opt/sentinelone/bin/sentinelctl heap_trimming interval set ""
value: Invalid type, expected number
```

https://github.com/Sentinel-One/helm-charts/blob/d4b89212dde336c728c890e24f8b50b71b8935a6/charts/s1-agent/templates/agent/daemonset.yaml#L66

Tested with `22.3.1`, `22.3.3` and ``22.4.1``

**Comment by oded-s1** [comment]
Thanks!
We fixed the typo in deployment.sh
